### ISSUE TITLE
Peer review for team Vitiz by team Visulas

### ISSUE THREAD

**Issue by virensasalu** [INFO-526-FA24/project-2-vizit#1]
Viren Sasalu, Bhaskar Bijoy Kashyap, Gaurangi Raul, Tushar Vimal for Visual Voyagers. @virensasalu @bhaskar-237 @gr98765 @tusharvimal

2. Goal of the project:
Analyze the readmission patterns across 130 hospitals over 10 years

3. Describe the data used:
The data used are hospital records pertaining to diabetes patients who stayed for 14 days, and the aim is to identify early readmissions

4. Describe how the questions/approaches will be used:

- Question 1: The question will be answered using descriptive statistics, a correlation matrix between the independent variables and visualizing the results using bar charts and box plots while grouping by different demographics.

- Question 2: Chi-square test to determine if each diagnosis category is related to readmission, compare non-diabetic vs diabetic patients with respect to readmissions and visualizing it using bar plots. Help find out the key metrics that drive readmissions.

- Question 3: How do prior healthcare utilization and patient characteristics influence readmission, and which groups should be prioritized for follow-up care? Objective: To determine which factors (including previous healthcare visits, diagnoses, and treatments) predict hospital readmission, and identify high-risk groups that require focused follow-up.
The team will looking will be looking at the variables:  -n_outpatient\`, \`n_inpatient\`, \`n_emergency\` -\`age\` -\`medical_specialty\` -\`time_in_hospital\`, \`n_medications\`, \`n_procedures\` -\`diag_1\`, \`diag_2\`, \`diag_3\` -\`diabetes_med\`, \`change\` -\`readmitted\`
Information avaliable from this attributes must be more than enough. Although visualizing them and using all of these attribute could prove to be a hectic task. 
The team will be looking forward to perform some predictive modeling like logistics, random forest to identify some predictors of readmission.

5. Is there anything unclear:
The approach looks good and the plan is structured well. 

6. Constructive feedback:
We like your project. It is well-structured and aimed at addressing an important healthcare question. To enhance your analysis, consider incorporating statistical tests like chi-squared or t-tests to first establish the significance of differences in readmission rates between diabetic and non-diabetic patients before applying predictive models, ensuring a robust foundation for your conclusions.

7. what aspect of the project are you most interested and looking forward to see highlighted:
The question, "Some doctors believe diabetes might play a central role in readmission. Explore the effect of a diabetes diagnosis on readmission rates. Objective: To validate the hypothesis that a diabetes diagnosis significantly impacts readmission rates." seems exciting as diabetes is a debilitating issue and we are looking forward to learning more about it. The attributes used to tackle this questions is good. Looking forward from some insights and visuals. 

8. Feedback on issues:
- Missing Read me file
- Missing about file

9. Comments: 
Looking forward to some exciting visuals

Team - Visual Voyagers

**Comment by junaidhussain22** [comment]
Based on their feedback we will be incorporating relevant hypothesis tests like chi-square and t-tests in order to affirm the findings as relevant based on the prior analysis we wish to do .
