### ISSUE TITLE
Review from team Data Nexus

### ISSUE THREAD

**Issue by SiddheshwarSinghNegi** [INFO-526-FA24/project-2-vizit#10]
Strengths: The visuals in the project are self-explanatory and effectively convey the underlying data and insights without requiring extensive additional explanation. The choice of a unique and innovative topic adds to the project's appeal, showcasing creativity and thoughtfulness in selecting a subject that stands out from conventional themes.

Weaknesses: While forest plots are used to represent data, they might pose a challenge for audiences unfamiliar with such visualizations. This can hinder their ability to fully grasp the information being presented. Exploring alternative visualization techniques that are more intuitive or universally understood could improve accessibility and engagement.

**Comment by anu3biswas** [comment]
Thank you.
