### ISSUE TITLE
Review by Team Insight Decoders

### ISSUE THREAD

**Issue by hemabk** [INFO-526-FA24/project-2-vizit#12]
Hello Team Vizit,

Strengths:
1) The project features a detailed and well-designed plot, effectively visualizing unique data on hospital readmissions.
2) The analysis highlights important factors with clarity and precision.

Weaknesses:
1) The use of a forest plot may not be the most effective choice for this data; an alternative visualization could enhance clarity.
2) Exploring other plot types could make the findings more accessible and engaging for the audience.

**Comment by anu3biswas** [comment]
I believe forest plot is the best way to depict odd ratios.
