### ISSUE TITLE
Instructor review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-vizit#3]
Hello team ViZit

Overall, your proposal indicates that you are set up for a success. You have a data set that will be able to answer the research questions through the proposed analysis and visualizations. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |      3  |
| Proposal | 5         |    5    |
| Workflow | 1         |    1    |
| Teamwork | 1         |     1   |
| Total    | 10        |   10    |

**Comment by anu3biswas** [comment]
Thank you.
