### ISSUE TITLE
Peer Review of iShowcase Poster by Team DataWaves

### ISSUE THREAD

**Issue by iam-ajeetsingh** [INFO-526-FA24/project-2-vizit#4]
Hello Team Vizit,

**Your research addresses an interesting and crucial topic in Healthcare.** 

Here are my observations regarding your poster:

**Positive Aspects:**
The use of specific plots has allowed you to derive fascinating insights and conclusions.

**Areas for Enhancement:**
1.There is a scope to improve the poster's formatting to enhance its overall aesthetic appeal.
2. Adding a section on the future scope of the work would provide valuable insight into potential directions for further research.

Overall, Great Work.

**Comment by anu3biswas** [comment]
Thank you.
